# prettier-ignore

services:
  postgres-db:
    image: postgres:16.4
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB:  ${DATABASE_NAME}        
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_USER_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - ./database:/var/lib/postgresql/data/pgdata
 nestjs-app:
    build: .
    ports:
      - ${SERVER_PORT}:3000
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_HOST: postgres-db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_USER_PASSWORD: ${DATABASE_USER_PASSWORD}
      PASSPORT_SECRET: ${PASSPORT_SECRET}
    depends_on:
      - postgres-db