# prettier-ignore

services:
  postgres-db:
    image: postgres:16.4
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB:  ${DATABASE_NAME}        
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_USER_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - ./database:/var/lib/postgresql/data/pgdata
