import { Link } from '@links/entities/link.entity';

export const USERS = [
  {
    id: '1223423',
    username: 'johnDoe',
    firstName: 'John',
    lastName: 'Doe',
    email: 'johndoe@gmail.com',
    password: 'hashPassword123*qdw',
    createdAt: new Date(),
    updatedAt: new Date(),
    links: null,
    checkProperties: () => {},
  },
  {
    id: '2342352',
    username: 'janeSmith',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'janesmith@gmail.com',
    password: 'hashPassword456*qdw',
    createdAt: new Date(),
    updatedAt: new Date(),
    links: null,
    checkProperties: () => {},
  },
  {
    id: '3453463',
    username: 'mikeJohnson',
    firstName: 'Mike',
    lastName: 'Johnson',
    email: 'mikejohnson@gmail.com',
    password: 'hashPassword789*qdw',
    createdAt: new Date(),
    updatedAt: new Date(),
    links: null,
    checkProperties: () => {},
  },
  {
    id: '4564574',
    username: 'emilyBrown',
    firstName: 'Emily',
    lastName: 'Brown',
    email: 'emilybrown@gmail.com',
    password: 'hashPassword321*qdw',
    createdAt: new Date(),
    updatedAt: new Date(),
    links: null,
    checkProperties: () => {},
  },
  {
    id: '5675685',
    username: 'chrisDavis',
    firstName: 'Chris',
    lastName: 'Davis',
    email: 'chrisdavis@gmail.com',
    password: 'hashPassword654*qdw',
    createdAt: new Date(),
    updatedAt: new Date(),
    links: null,
    checkProperties: () => {},
  },
];

export const LINKS: Link[] = [
  {
    id: '98ead8a7-eea9-4b1a-a285-7021eea5d3c3',
    urlOriginal: 'https://es.wikipedia.org/wiki/Viacheslav_von_Pleve',
    shortURL: '2x313',
    status: false,
    expirationDate: new Date('July 20 2025, 69 00:20:18'),
    visits: [],
    user: null,
    updatedAt: new Date(),
    createdAt: new Date(),
    setExpirationDate: () => {},
  },
  {
    id: '5dd5ea13-f377-473e-89da-0586a4f5f484',
    urlOriginal:
      'https://es.wikipedia.org/wiki/Copa_Libertadores_Femenina_2024',
    shortURL: '2x311',
    status: true,
    expirationDate: new Date('July 20 2025, 69 00:20:18'),
    visits: [],
    user: null,
    updatedAt: new Date(),
    createdAt: new Date(),
    setExpirationDate: () => {},
  },
  {
    id: '0bc8a6b8-1b3b-47b2-b1a4-2f4e5a170201',
    urlOriginal: 'https://es.wikipedia.org/wiki/Torneo_de_Pek%C3%ADn_2024',
    shortURL: '2x312',
    status: true,
    expirationDate: new Date('July 20 2025, 69 00:20:18'),
    visits: [],
    user: null,
    updatedAt: new Date(),
    createdAt: new Date(),
    setExpirationDate: () => {},
  },
];
