export const USERS = [
  {
    id: '1223423',
    username: 'johnDoe',
    firstName: 'John',
    lastName: 'Doe',
    email: 'johndoe@gmail.com',
    password: 'hashPassword123*qdw',
    createdAt: new Date(),
    updatedAt: new Date(),
    links: null,
    checkProperties: jest.fn(),
  },
  {
    id: '2342352',
    username: 'janeSmith',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'janesmith@gmail.com',
    password: 'hashPassword456*qdw',
    createdAt: new Date(),
    updatedAt: new Date(),
    links: null,
    checkProperties: jest.fn(),
  },
  {
    id: '3453463',
    username: 'mikeJohnson',
    firstName: 'Mike',
    lastName: 'Johnson',
    email: 'mikejohnson@gmail.com',
    password: 'hashPassword789*qdw',
    createdAt: new Date(),
    updatedAt: new Date(),
    links: null,
    checkProperties: jest.fn(),
  },
  {
    id: '4564574',
    username: 'emilyBrown',
    firstName: 'Emily',
    lastName: 'Brown',
    email: 'emilybrown@gmail.com',
    password: 'hashPassword321*qdw',
    createdAt: new Date(),
    updatedAt: new Date(),
    links: null,
    checkProperties: jest.fn(),
  },
  {
    id: '5675685',
    username: 'chrisDavis',
    firstName: 'Chris',
    lastName: 'Davis',
    email: 'chrisdavis@gmail.com',
    password: 'hashPassword654*qdw',
    createdAt: new Date(),
    updatedAt: new Date(),
    links: null,
    checkProperties: jest.fn(),
  },
];
